### ISSUE TITLE
Internal Server Error with Spider on any field query

### ISSUE THREAD

**Issue by sumanyu** [dell-oss/Doradus#6] opened 2015-08-18 17:59 UTC
I was trying out any field query as per: https://github.com/dell-oss/Doradus/wiki/Text-Contains-Clauses%20(Spider) and I got internal server error response from doradus. Is this intended?

```
500 Internal Server Error: java.lang.NullPointerException
	at com.dell.doradus.service.spider.SpiderHelper.getFields(SpiderHelper.java:569)
	at com.dell.doradus.search.builder.BuilderBinary.search(BuilderBinary.java:59)
	at com.dell.doradus.search.Searcher.search(Searcher.java:115)
	at com.dell.doradus.search.builder.BuilderAnd.search(BuilderAnd.java:42)
	at com.dell.doradus.search.Searcher.search(Searcher.java:115)
	at com.dell.doradus.search.Searcher.search(Searcher.java:97)
	at com.dell.doradus.search.QueryExecutor.search(QueryExecutor.java:119)
	at com.dell.doradus.search.QueryExecutor.search(QueryExecutor.java:113)
	at com.dell.doradus.search.QueryExecutor.search(QueryExecutor.java:84)
	at com.dell.doradus.service.spider.ObjectQuery.query(ObjectQuery.java:304)
	at com.dell.doradus.service.spider.SpiderService.objectQueryURI(SpiderService.java:194)
	at com.dell.doradus.service.spider.QueryURICmd.invokeUNodeOut(QueryURICmd.java:34)
	at com.dell.doradus.service.rest.UNodeOutCallback.invoke(UNodeOutCallback.java:39)
	at com.dell.doradus.service.rest.RESTServlet.validateAndExecuteRequest(RESTServlet.java:162)
	at com.dell.doradus.service.rest.RESTServlet.doGet(RESTServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:517)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

Example: _query?q=*:(sflksjf)

**Comment by RandyGuck** [comment] 2015-08-18 19:33
Thanks for pointing out the error. I went through all the examples on the wiki page as well as your query sample and couldn't reproduce the problem. If your schema is not proprietary, could you send it to me so we can see if it has anything peculiar? Also, are you using the latest release from the master branch, or an older version? Thanks.

**Comment by sumanyu** [comment] 2015-08-19 00:18
We're using release 2.3. Here's the schema: https://gist.github.com/sumanyu/eb50fa6a1fcf7ba62a4c

**Comment by RandyGuck** [comment] 2015-08-19 17:15
I was able to reproduce the problem with 2_3_0 branch and verified that it is fixed in the latest (master) branch. We're within a week or two of tagging the master branch for the v2.4 release and creating a new branch for it. But master should be fairly stable, so if possible, please use it to get the fix. Thanks.

**Comment by sumanyu** [comment] 2015-08-19 20:24
Thanks

**Closed** 2015-08-19 22:57 UTC
